version: "3.8"

services:
  db:
    image: postgis/postgis:15-3.4
    container_name: postgis-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: [REDACTED]
      POSTGRES_DB: spatialdb
    ports:
      - "5433:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

